//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSoftware.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemSoftware.Resources.ConsoleMessages", typeof(ConsoleMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновлено все.
        /// </summary>
        internal static string ApplicationRefreshed {
            get {
                return ResourceManager.GetString("ApplicationRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Программа завершила свои действия. Запустите ее заново.
        /// </summary>
        internal static string ApplicationRunEnded {
            get {
                return ResourceManager.GetString("ApplicationRunEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала нужно произвести 1 проход.
        /// </summary>
        internal static string Error_FirstRunNotExecuted {
            get {
                return ResourceManager.GetString("Error_FirstRunNotExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый ключ. Должен быть -INPUT_FILE.
        /// </summary>
        internal static string Error_InputFileArgument {
            get {
                return ResourceManager.GetString("Error_InputFileArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить данные с файла. Возможно путь к файлу указан неверно.
        /// </summary>
        internal static string Error_InputFileNotFound {
            get {
                return ResourceManager.GetString("Error_InputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый ключ. Должен быть -OUTPUT_FILE.
        /// </summary>
        internal static string Error_OutputFileArgument {
            get {
                return ResourceManager.GetString("Error_OutputFileArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись не успешна, возможно не задан или не найден файл.
        /// </summary>
        internal static string Error_OutputFileNotFound {
            get {
                return ResourceManager.GetString("Error_OutputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное количество аргументов.
        /// </summary>
        internal static string Error_WrongArgumentsCount {
            get {
                return ResourceManager.GetString("Error_WrongArgumentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное использование аргументов командной строки.
        /// </summary>
        internal static string Error_WrongCommandLineArguments {
            get {
                return ResourceManager.GetString("Error_WrongCommandLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка:.
        /// </summary>
        internal static string ErrorPrefix {
            get {
                return ResourceManager.GetString("ErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 проход завершен.
        /// </summary>
        internal static string FirstRunEnded {
            get {
                return ResourceManager.GetString("FirstRunEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступные ключи.
        /// </summary>
        internal static string Help_AllowedKeys {
            get {
                return ResourceManager.GetString("Help_AllowedKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если путь к файлу имеет пробелы - следует заключить его в кавычки.
        /// </summary>
        internal static string Help_Footer {
            get {
                return ResourceManager.GetString("Help_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вызов данной справки.
        /// </summary>
        internal static string Help_HelpKey {
            get {
                return ResourceManager.GetString("Help_HelpKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ для указания пути к файлу с исходным текстом.
        /// </summary>
        internal static string Help_InputFileKey {
            get {
                return ResourceManager.GetString("Help_InputFileKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ для указания пути сохранения результирующего ассемблерного кода.
        /// </summary>
        internal static string Help_OutputFileKey {
            get {
                return ResourceManager.GetString("Help_OutputFileKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка по данной программе.
        /// </summary>
        internal static string Help_Title {
            get {
                return ResourceManager.GetString("Help_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить 1 проход.
        /// </summary>
        internal static string Menu_FirstRun {
            get {
                return ResourceManager.GetString("Menu_FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаг вперед.
        /// </summary>
        internal static string Menu_NextStep {
            get {
                return ResourceManager.GetString("Menu_NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Распечатать Ассемблерный код.
        /// </summary>
        internal static string Menu_PrintAssemblerCode {
            get {
                return ResourceManager.GetString("Menu_PrintAssemblerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Распечатать ТМО.
        /// </summary>
        internal static string Menu_PrintMacrosTable {
            get {
                return ResourceManager.GetString("Menu_PrintMacrosTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Распечатать Исходный код.
        /// </summary>
        internal static string Menu_PrintSourceCode {
            get {
                return ResourceManager.GetString("Menu_PrintSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Распечатать Таблицу глобальных переменных.
        /// </summary>
        internal static string Menu_PrintVariablesTable {
            get {
                return ResourceManager.GetString("Menu_PrintVariablesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать заново.
        /// </summary>
        internal static string Menu_Refresh {
            get {
                return ResourceManager.GetString("Menu_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Распечатать Ассемблерный код в файл.
        /// </summary>
        internal static string Menu_SaveAssemblerCodeIntoFile {
            get {
                return ResourceManager.GetString("Menu_SaveAssemblerCodeIntoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить 2 проход.
        /// </summary>
        internal static string Menu_SecondRun {
            get {
                return ResourceManager.GetString("Menu_SecondRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка в строке.
        /// </summary>
        internal static string Prefix_ErrorInstring {
            get {
                return ResourceManager.GetString("Prefix_ErrorInstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ассемблерный код.
        /// </summary>
        internal static string Print_AssemblerCode {
            get {
                return ResourceManager.GetString("Print_AssemblerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТМО.
        /// </summary>
        internal static string Print_MacrosTable {
            get {
                return ResourceManager.GetString("Print_MacrosTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходный код.
        /// </summary>
        internal static string Print_SourceCode {
            get {
                return ResourceManager.GetString("Print_SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица глобальных переменных.
        /// </summary>
        internal static string Print_VariablesTable {
            get {
                return ResourceManager.GetString("Print_VariablesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись успешна.
        /// </summary>
        internal static string SaveIntoFileSuccess {
            get {
                return ResourceManager.GetString("SaveIntoFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2 проход завершен. Перезапустите программу.
        /// </summary>
        internal static string SecondRunEnded {
            get {
                return ResourceManager.GetString("SecondRunEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очередной шаг выполнен.
        /// </summary>
        internal static string StepExecuted {
            get {
                return ResourceManager.GetString("StepExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раз уж начали выполнять прогу по частям, а не по шагам, так и нечего сюда лезть.
        /// </summary>
        internal static string StepModeActivated {
            get {
                return ResourceManager.GetString("StepModeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введен неверный ключ.
        /// </summary>
        internal static string WrongKeyEntered {
            get {
                return ResourceManager.GetString("WrongKeyEntered", resourceCulture);
            }
        }
    }
}
